In [14]:
#Importing Libraries
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd
import os

In [15]:
#List of the symptoms is listed here in list l1.
l1=['back_pain','constipation','abdominal_pain','diarrhoea','mild_fever','yellow_urine',
    'yellowing_of_eyes','acute_liver_failure','fluid_overload','swelling_of_stomach',
    'swelled_lymph_nodes','malaise','blurred_and_distorted_vision','phlegm','throat_irritation',
    'redness_of_eyes','sinus_pressure','runny_nose','congestion','chest_pain','weakness_in_limbs',
    'fast_heart_rate','pain_during_bowel_movements','pain_in_anal_region','bloody_stool',
    'irritation_in_anus','neck_pain','dizziness','cramps','bruising','obesity','swollen_legs',
    'swollen_blood_vessels','puffy_face_and_eyes','enlarged_thyroid','brittle_nails',
    'swollen_extremeties','excessive_hunger','extra_marital_contacts','drying_and_tingling_lips',
    'slurred_speech','knee_pain','hip_joint_pain','muscle_weakness','stiff_neck','swelling_joints',
    'movement_stiffness','spinning_movements','loss_of_balance','unsteadiness',
    'weakness_of_one_body_side','loss_of_smell','bladder_discomfort','foul_smell_of urine',
    'continuous_feel_of_urine','passage_of_gases','internal_itching','toxic_look_(typhos)',
    'depression','irritability','muscle_pain','altered_sensorium','red_spots_over_body','belly_pain',
    'abnormal_menstruation','dischromic _patches','watering_from_eyes','increased_appetite','polyuria','family_history','mucoid_sputum',
    'rusty_sputum','lack_of_concentration','visual_disturbances','receiving_blood_transfusion',
    'receiving_unsterile_injections','coma','stomach_bleeding','distention_of_abdomen',
    'history_of_alcohol_consumption','fluid_overload','blood_in_sputum','prominent_veins_on_calf',
    'palpitations','painful_walking','pus_filled_pimples','blackheads','scurring','skin_peeling',
    'silver_like_dusting','small_dents_in_nails','inflammatory_nails','blister','red_sore_around_nose',
    'yellow_crust_ooze']



In [16]:
disease=['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo']



In [17]:
l2=[]
for i in range(0,len(l1)):
    l2.append(0)
print(l2)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [18]:
df=pd.read_csv("trainingset.csv")

In [19]:
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [70]:
DF= pd.read_csv('trainingset.csv', index_col='prognosis')

In [20]:

df.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
    'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
    'Migraine':11,'Cervical spondylosis':12,
    'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
    'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
    'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
    'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
    '(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
    'Impetigo':40}},inplace=True)
#df.head()
DF.head()

NameError: name 'DF' is not defined

In [21]:
X= df[l1]
y = df[["prognosis"]]
np.ravel(y)
print(X)

      back_pain  constipation  abdominal_pain  diarrhoea  mild_fever  \
0             0             0               0          0           0   
1             0             0               0          0           0   
2             0             0               0          0           0   
3             0             0               0          0           0   
4             0             0               0          0           0   
...         ...           ...             ...        ...         ...   
4956          0             0               0          0           0   
4957          0             0               0          0           0   
4958          0             0               0          0           0   
4959          0             0               0          0           0   
4960          0             0               0          0           0   

      yellow_urine  yellowing_of_eyes  acute_liver_failure  fluid_overload  \
0                0                  0                    

In [73]:
print(y)

      prognosis
0             0
1             0
2             0
3             0
4             0
...         ...
4956         36
4957         37
4958         38
4959         39
4960         40

[4961 rows x 1 columns]


In [23]:
#Reading the  testing.csv file
tr=pd.read_csv("testingset.csv")

#Using inbuilt function replace in pandas for replacing the values

tr.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
    'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
    'Migraine':11,'Cervical spondylosis':12,
    'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
    'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
    'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
    'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
    '(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
    'Impetigo':40}},inplace=True)
tr.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   
3        1          0                     0                    0          0   
4        1          1                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   
3       0           0             0        0                 0  ...   
4       0           0             1        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze  prognosis  
0                  0          0  
1                  0          1  
2                  0          2  
3                  0          3  
4                  0          4  

[5 rows x 133 columns]

In [24]:
X_test= tr[l1]
y_test = tr[["prognosis"]]
np.ravel(y_test)
print(X_test)

    back_pain  constipation  abdominal_pain  diarrhoea  mild_fever  \
0           0             0               0          0           0   
1           0             0               0          0           0   
2           0             0               0          0           0   
3           0             0               1          0           0   
4           0             0               0          0           0   
5           0             0               1          0           0   
6           0             0               0          0           0   
7           0             0               0          0           0   
8           0             0               0          1           0   
9           0             0               0          0           0   
10          0             0               0          0           0   
11          0             0               0          0           0   
12          1             0               0          0           0   
13          0       

In [25]:
print(y_test)

    prognosis
0           0
1           1
2           2
3           3
4           4
5           5
6           6
7           7
8           8
9           9
10         10
11         11
12         12
13         13
14         14
15         15
16         16
17         17
18         18
19         19
20         20
21         21
22         22
23         23
24         24
25         25
26         26
27         27
28         28
29         29
30         30
31         31
32         32
33         33
34         34
35         35
36         36
37         37
38         38
39         39
40         40


In [26]:


def scatterinp(sym1,sym2,sym3,sym4,sym5):
    x = [sym1,sym2,sym3,sym4,sym5]#storing input symptoms in y
    y = [0,0,0,0,0]#creating and giving values to the input symptoms
    if(sym1!='Select Here'):
        y[0]=1
    if(sym2!='Select Here'):
        y[1]=1
    if(sym3!='Select Here'):
        y[2]=1
    if(sym4!='Select Here'):
        y[3]=1
    if(sym5!='Select Here'):
        y[4]=1
    print(x)
    print(y)
    plt.scatter(x,y)
    plt.show()

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
gnb = GaussianNB()
gnb=gnb.fit(X,np.ravel(y))
        # y_pred_gnb = gnb.predict(X_test)

        # k-Nearest Neighbors
knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn=knn.fit(X,np.ravel(y))
        # y_pred_knn = knn.predict(X_test)

        # Create an ensemble model using majority voting
        # ensemble_model = VotingClassifier(estimators=[('gnb', gnb), ('knn', knn)], voting='hard')
        # # Fit the ensemble model on the training data
        # ensemble_model.fit(X, np.ravel(y))

        # # Make predictions on the test data
y_pred_ensemble = model.predict(X_test)

        #Save model
        # model_filename = 'ensemble_model.pkl'
        # joblib.dump(ensemble_model, model_filename)



        # model_filename = 'ensemble_model.pkl'
        # joblib.dump(ensemble_model, model_filename)


        # saveData()
        # import pickle
        # model_filename = 'ensemble_model.pkl'
        # with open(model_filename, 'wb') as file:
        #     pickle.dump(ensemble_model, file)
        # name='ensemble.pkl'
        # pickle.dump(ensemble_model,open(name,'wb'))
        # from sklearn.externals import joblib
        # model_filename = 'ensemble_model.pkl'
        # joblib.dump(ensemble_model, model_filename)
        
         # Print accuracy and confusion matrix for the ensemble model
print("Ensemble Model (GNB + KNN)")
print("Accuracy")
print(accuracy_score(y_test, y_pred_ensemble))
print("Confusion matrix")
conf_matrix_ensemble = confusion_matrix(y_test, y_pred_ensemble)
print(conf_matrix_ensemble)


        # Collect symptoms directly from user input
psymptoms = [Symptom1.get(), Symptom2.get(), Symptom3.get(), Symptom4.get(), Symptom5.get()]

for k in range(0,len(l1)):
    for z in psymptoms:
        if(z==l1[k]):
            l2[k]=1
inputtest = [l2]

        # Make predictions on the test data
y_pred_ensemble = ensemble_model.predict(inputtest)
        
        # Print accuracy and confusion matrix for the ensemble model
print("Ensemble Model (GNB + KNN)")
print("Predicted Disease Index:", y_pred_ensemble[0])
print("Disease List:", disease)

predicted = y_pred_ensemble[0]
if 0 <= predicted < len(disease):
    pred1.set(disease[predicted])
else:
    pred1.set("Not Found")

In [78]:
#ensemble
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import sqlite3


root = Tk()
pred1=StringVar()
def ensembleModel():
    if len(NameEn.get()) == 0:
        pred1.set(" ")
        comp = messagebox.askokcancel("System", "Kindly Fill the Name")
        if comp:
            root.mainloop()
    elif Symptom1.get() == "Select Here" or Symptom2.get() == "Select Here":
        pred1.set(" ")
        sym = messagebox.askokcancel("System", "Kindly Fill at least first two Symptoms")
        if sym:
            root.mainloop()
    else:
        # Gaussian Naive Bayes
        gnb = GaussianNB()
        gnb=gnb.fit(X,np.ravel(y))
        # y_pred_gnb = gnb.predict(X_test)

        # k-Nearest Neighbors
        knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
        knn=knn.fit(X,np.ravel(y))
        # y_pred_knn = knn.predict(X_test)

        # Create an ensemble model using majority voting
        ensemble_model = VotingClassifier(estimators=[('gnb', gnb), ('knn', knn)], voting='hard')
        # Fit the ensemble model on the training data
        ensemble_model.fit(X, np.ravel(y))

        # Make predictions on the test data
        y_pred_ensemble = ensemble_model.predict(X_test)

        #Save model
        # model_filename = 'ensemble_model.pkl'
        # joblib.dump(ensemble_model, model_filename)



        # model_filename = 'ensemble_model.pkl'
        # joblib.dump(ensemble_model, model_filename)


        # saveData()
        # import pickle
        # model_filename = 'ensemble_model.pkl'
        # with open(model_filename, 'wb') as file:
        #     pickle.dump(ensemble_model, file)
        # name='ensemble.pkl'
        # pickle.dump(ensemble_model,open(name,'wb'))
        # from sklearn.externals import joblib
        # model_filename = 'ensemble_model.pkl'
        # joblib.dump(ensemble_model, model_filename)
        
         # Print accuracy and confusion matrix for the ensemble model
        print("Ensemble Model (GNB + KNN)")
        print("Accuracy")
        print(accuracy_score(y_test, y_pred_ensemble))
        print("Confusion matrix")
        conf_matrix_ensemble = confusion_matrix(y_test, y_pred_ensemble)
        print(conf_matrix_ensemble)


        # Collect symptoms directly from user input
        psymptoms = [Symptom1.get(), Symptom2.get(), Symptom3.get(), Symptom4.get(), Symptom5.get()]

        for k in range(0,len(l1)):
            for z in psymptoms:
                if(z==l1[k]):
                    l2[k]=1
        inputtest = [l2]

        # Make predictions on the test data
        y_pred_ensemble = ensemble_model.predict(inputtest)
        
        # Print accuracy and confusion matrix for the ensemble model
        print("Ensemble Model (GNB + KNN)")
        print("Predicted Disease Index:", y_pred_ensemble[0])
        print("Disease List:", disease)

        predicted = y_pred_ensemble[0]
        if 0 <= predicted < len(disease):
            pred1.set(disease[predicted])
        else:
            pred1.set("Not Found")

        import pickle
        model_filename = 'ensemble_model.pkl'
        with open(model_filename, 'wb') as file:
            pickle.dump(ensemble_model, file)



            
        # Creating the database if not exists named as database.db and creating table if not exists named as Ensemble using sqlite3
        conn = sqlite3.connect('database.db')
        c = conn.cursor()
        c.execute("CREATE TABLE IF NOT EXISTS Ensemble(Name TEXT, Symptom1 TEXT, Symptom2 TEXT, Symptom3 TEXT, Symptom4 TEXT, Symptom5 TEXT, Disease TEXT)")
        c.execute("INSERT INTO Ensemble(Name, Symptom1, Symptom2, Symptom3, Symptom4, Symptom5, Disease) VALUES(?,?,?,?,?,?,?)",
                  (NameEn.get(), Symptom1.get(), Symptom2.get(), Symptom3.get(), Symptom4.get(), Symptom5.get(), pred1.get()))
        conn.commit()
        c.close()
        conn.close()



In [79]:
# import pickle
# model_filename = 'ensemble_model.pkl'
# with open(model_filename, 'wb') as file:
#     pickle.dump(ensemble_model, file)

GUI

In [80]:
#Tk class is used to create a root window
root.configure(background='Ivory')
root.title('Smart Disease Predictor System')
root.resizable(0,0)

''

In [81]:
Symptom1 = StringVar()
Symptom1.set("Select Here")

Symptom2 = StringVar()
Symptom2.set("Select Here")

Symptom3 = StringVar()
Symptom3.set("Select Here")

Symptom4 = StringVar()
Symptom4.set("Select Here")

Symptom5 = StringVar()
Symptom5.set("Select Here")
Name = StringVar()

In [82]:
prev_win=None
def Reset():
    global prev_win

    Symptom1.set("Select Here")
    Symptom2.set("Select Here")
    Symptom3.set("Select Here")
    Symptom4.set("Select Here")
    Symptom5.set("Select Here")
    Name.delete(first=0,last=100)
    pred1.set(" ")
    
    try:
        prev_win.destroy()
        prev_win=None
    except AttributeError:
        pass

In [83]:
from tkinter import messagebox
def Exit():
    qExit=messagebox.askyesno("System","Do you want to exit the system")
    
    if qExit:
        root.destroy()
        exit()

In [84]:
#Headings for the GUI written at the top of GUI
w2 = Label(root, justify=LEFT, text="Disease Predictor using Machine Learning", fg="Red", bg="Ivory")
w2.config(font=("Times",30,"bold italic"))
w2.grid(row=1, column=0, columnspan=2, padx=100)
w2.config(font=("Times",30,"bold italic"))
w2.grid(row=2, column=0, columnspan=2, padx=100)

In [85]:
#Label for the name
NameLb = Label(root, text="Name of the Patient *", fg="Red", bg="Ivory")
NameLb.config(font=("Times",15,"bold italic"))
NameLb.grid(row=6, column=0, pady=15, sticky=W)

In [86]:
#Creating Labels for the symtoms
S1Lb = Label(root, text="Symptom 1 *", fg="Black", bg="Ivory")
S1Lb.config(font=("Times",15,"bold italic"))
S1Lb.grid(row=7, column=0, pady=10, sticky=W)

S2Lb = Label(root, text="Symptom 2 *", fg="Black", bg="Ivory")
S2Lb.config(font=("Times",15,"bold italic"))
S2Lb.grid(row=8, column=0, pady=10, sticky=W)

S3Lb = Label(root, text="Symptom 3", fg="Black",bg="Ivory")
S3Lb.config(font=("Times",15,"bold italic"))
S3Lb.grid(row=9, column=0, pady=10, sticky=W)

S4Lb = Label(root, text="Symptom 4", fg="Black", bg="Ivory")
S4Lb.config(font=("Times",15,"bold italic"))
S4Lb.grid(row=10, column=0, pady=10, sticky=W)

S5Lb = Label(root, text="Symptom 5", fg="Black", bg="Ivory")
S5Lb.config(font=("Times",15,"bold italic"))
S5Lb.grid(row=11, column=0, pady=10, sticky=W)

In [87]:
#Labels for the different algorithms
lrLb = Label(root, text="Prediction", fg="white", bg="red", width = 20)
lrLb.config(font=("Times",15,"bold italic"))
lrLb.grid(row=15, column=0, pady=10,sticky=W)


OPTIONS = sorted(l1)

In [88]:
#Taking name as input from user
NameEn = Entry(root, textvariable=Name)
NameEn.grid(row=6, column=1)

#Taking Symptoms as input from the dropdown from the user
S1 = OptionMenu(root, Symptom1,*OPTIONS)
S1.grid(row=7, column=1)

S2 = OptionMenu(root, Symptom2,*OPTIONS)
S2.grid(row=8, column=1)

S3 = OptionMenu(root, Symptom3,*OPTIONS)
S3.grid(row=9, column=1)

S4 = OptionMenu(root, Symptom4,*OPTIONS)
S4.grid(row=10, column=1)

S5 = OptionMenu(root, Symptom5,*OPTIONS)
S5.grid(row=11, column=1)

In [89]:
#Buttons for predicting the disease using different algorithms
# dst = Button(root, text="Predict", command=ensembleModel,bg="Red",fg="yellow")
# dst.config(font=("Times",15,"bold italic"))
# Modify your button command to call ensembleModel instead of DecisionTree
ensembleButton = Button(root, text="Ensemble Model", command=ensembleModel, bg="Red",fg="yellow")
ensembleButton.config(font=("Times",15,"bold italic"))
ensembleButton.grid(row=6, column=3,padx=10)
# button.pack()

# root.mainloop()


rs = Button(root,text="Reset Inputs", command=Reset,bg="yellow",fg="purple",width=15)
rs.config(font=("Times",15,"bold italic"))
rs.grid(row=10,column=3,padx=10)

ex = Button(root,text="Exit System", command=Exit,bg="yellow",fg="purple",width=15)
ex.config(font=("Times",15,"bold italic"))
ex.grid(row=11,column=3,padx=10)

In [90]:
#Showing the output of different aldorithms
t1=Label(root,font=("Times",15,"bold italic"),text="Ensemble Model",height=1,bg="Light green"
         ,width=40,fg="red",textvariable=pred1,relief="sunken").grid(row=15, column=1, padx=10)



In [91]:
#calling this function because the application is ready to run
root.mainloop()

Ensemble Model (GNB + KNN)
Accuracy
0.9512195121951219
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Ensemble Model (GNB + KNN)
Predicted Disease Index: 8
Disease List: ['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis', 'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ', 'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine', 'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice', 'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A', 'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E', 'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia', 'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins', 'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia', 'Osteoarthristis', 'Arthritis', '(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'Urinary tract infection', 'Psoriasis', 'Impetigo']


d:\project\a\Symptom_Prediction\.venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
d:\project\a\Symptom_Prediction\.venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


Ensemble Model (GNB + KNN)
Accuracy
0.9512195121951219
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Ensemble Model (GNB + KNN)
Predicted Disease Index: 8
Disease List: ['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis', 'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ', 'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine', 'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice', 'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A', 'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E', 'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia', 'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins', 'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia', 'Osteoarthristis', 'Arthritis', '(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'Urinary tract infection', 'Psoriasis', 'Impetigo']


d:\project\a\Symptom_Prediction\.venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
d:\project\a\Symptom_Prediction\.venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [27]:
with open("fin.pkl", "rb") as file:
    model = pickle.load(file)

# The model has now been deserialized, next is to make use of it as you normally would.
# prediction = model.predict([[2,112,68,22,94,34.1,0.315,26]]) # Passing in variables for prediction
# print("The result is",prediction[0]) # Printing result
    

In [8]:
import pickle

In [12]:
psymptoms = ['back_pain','constipation','abdominal_pain','diarrhoea','mild_fever']
pred1= StringVar()
for k in range(0,len(l1)):
    for z in psymptoms:
        if(z==l1[k]):
            l2[k]=1
inputtest = [l2]

        # Make predictions on the test data
y_pred_ensemble = model.predict(inputtest)
        
        # Print accuracy and confusion matrix for the ensemble model
print("Ensemble Model (GNB + KNN)")
print("Predicted Disease Index:", y_pred_ensemble[0])
print("Disease List:", disease)

predicted = y_pred_ensemble[0]
if 0 <= predicted < len(disease):
    pred1.set(disease[predicted])
else:
    pred1.set("Not Found")
print(disease[predicted])

NameError: name 'StringVar' is not defined

In [13]:
y_pred_ensemble = model.predict(X_test)

NameError: name 'X_test' is not defined

In [95]:
print("Ensemble Model (GNB + KNN)")
print("Predicted Disease Index:", y_pred_ensemble[0])
print("Disease List:", disease)

Ensemble Model (GNB + KNN)
Predicted Disease Index: 0
Disease List: ['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis', 'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ', 'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine', 'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice', 'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A', 'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E', 'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia', 'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins', 'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia', 'Osteoarthristis', 'Arthritis', '(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'Urinary tract infection', 'Psoriasis', 'Impetigo']


In [97]:
print("Ensemble Model (GNB + KNN)")
print("Accuracy")
print(accuracy_score(y_test, y_pred_ensemble))
print("Confusion matrix")
conf_matrix_ensemble = confusion_matrix(y_test, y_pred_ensemble)
print(conf_matrix_ensemble)


 # Collect symptoms directly from user input
psymptoms = [Symptom1.get(), Symptom2.get(), Symptom3.get(), Symptom4.get(), Symptom5.get()]

for k in range(0,len(l1)):
    for z in psymptoms:
        if(z==l1[k]):
            l2[k]=1
inputtest = [l2]

        # Make predictions on the test data
y_pred_ensemble = model.predict(inputtest)
        
        # Print accuracy and confusion matrix for the ensemble model
print("Ensemble Model (GNB + KNN)")
print("Predicted Disease Index:", y_pred_ensemble[0])
print("Disease List:", disease)

predicted = y_pred_ensemble[0]
if 0 <= predicted < len(disease):
    pred1.set(disease[predicted])
else:
    pred1.set("Not Found")

Ensemble Model (GNB + KNN)
Accuracy
0.9512195121951219
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Ensemble Model (GNB + KNN)
Predicted Disease Index: 18
Disease List: ['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis', 'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ', 'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine', 'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice', 'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A', 'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E', 'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia', 'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins', 'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia', 'Osteoarthristis', 'Arthritis', '(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'Urinary tract infection', 'Psoriasis', 'Impetigo']


d:\project\a\Symptom_Prediction\.venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
d:\project\a\Symptom_Prediction\.venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [99]:
print(pred1)

PY_VAR9


In [100]:
print(disease[predicted])

Typhoid


In [30]:
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
gnb = GaussianNB()
# pred1="ab"
gnb=gnb.fit(X,np.ravel(y))
        # y_pred_gnb = gnb.predict(X_test)

        # k-Nearest Neighbors
knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn=knn.fit(X,np.ravel(y))
        # y_pred_knn = knn.predict(X_test)

        # Create an ensemble model using majority voting
        # ensemble_model = VotingClassifier(estimators=[('gnb', gnb), ('knn', knn)], voting='hard')
        # # Fit the ensemble model on the training data
        # ensemble_model.fit(X, np.ravel(y))

        # # Make predictions on the test data
y_pred_ensemble = model.predict(X_test)

        #Save model
        # model_filename = 'ensemble_model.pkl'
        # joblib.dump(ensemble_model, model_filename)



        # model_filename = 'ensemble_model.pkl'
        # joblib.dump(ensemble_model, model_filename)


        # saveData()
        # import pickle
        # model_filename = 'ensemble_model.pkl'
        # with open(model_filename, 'wb') as file:
        #     pickle.dump(ensemble_model, file)
        # name='ensemble.pkl'
        # pickle.dump(ensemble_model,open(name,'wb'))
        # from sklearn.externals import joblib
        # model_filename = 'ensemble_model.pkl'
        # joblib.dump(ensemble_model, model_filename)
        
         # Print accuracy and confusion matrix for the ensemble model
print("Ensemble Model (GNB + KNN)")
print("Accuracy")
print(accuracy_score(y_test, y_pred_ensemble))
print("Confusion matrix")
conf_matrix_ensemble = confusion_matrix(y_test, y_pred_ensemble)
print(conf_matrix_ensemble)


        # Collect symptoms directly from user input
psymptoms = ['back_pain','constipation','abdominal_pain','diarrhoea','mild_fever']

for k in range(0,len(l1)):
    for z in psymptoms:
        if(z==l1[k]):
            l2[k]=1
inputtest = [l2]

        # Make predictions on the test data
y_pred_ensemble = model.predict(inputtest)
        
        # Print accuracy and confusion matrix for the ensemble model
print("Ensemble Model (GNB + KNN)")
print("Predicted Disease Index:", y_pred_ensemble[0])
print("Disease List:", disease)

predicted = y_pred_ensemble[0]
if 0 <= predicted < len(disease):
    print(disease[predicted])
else:
    print("Not Found")

Ensemble Model (GNB + KNN)
Accuracy
0.9512195121951219
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Ensemble Model (GNB + KNN)
Predicted Disease Index: 18
Disease List: ['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis', 'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ', 'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine', 'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice', 'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A', 'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E', 'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia', 'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins', 'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia', 'Osteoarthristis', 'Arthritis', '(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'Urinary tract infection', 'Psoriasis', 'Impetigo']
Typhoid


d:\project\a\Symptom_Prediction\.venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
d:\project\a\Symptom_Prediction\.venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
